<a href="https://colab.research.google.com/github/kristoowae/Portofolio-Google_Notebook/blob/main/Introduction_to_Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Library

In [5]:
import numpy as np #library untuk matematika
import pandas as pd #library untuk dataframe
import seaborn as sns #library untuk visualisasi
import matplotlib.pyplot as plt

In [9]:
from google.colab import files

uploaded = files.upload()

Saving hotel_bookings.csv to hotel_bookings.csv

## Input Data

In [10]:
dataset = pd.read_csv('hotel_bookings.csv')
dataset.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,no,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,7/1/2015
1,Resort Hotel,no,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,7/1/2015
2,Resort Hotel,no,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,7/2/2015
3,Resort Hotel,no,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,7/2/2015
4,Resort Hotel,no,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,7/3/2015

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  object
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(15), object(13)
memory usage: 29.1+ MB

## Memebrsihkan Data

### Memeriksa nilai hilang

In [12]:
#Memeriksa persentase data hilang
dataset.isna().mean().round(3).mul(100)

hotel                              0.0
is_canceled                        0.0
lead_time                          0.0
arrival_date_year                  0.0
arrival_date_month                 0.0
arrival_date_week_number           0.0
arrival_date_day_of_month          0.0
stays_in_weekend_nights            0.0
stays_in_week_nights               0.0
adults                             0.0
children                           0.0
babies                             0.0
meal                               0.0
country                            0.4
market_segment                     0.0
distribution_channel               0.0
is_repeated_guest                  0.0
previous_cancellations             0.0
previous_bookings_not_canceled     0.0
reserved_room_type                 0.0
assigned_room_type                 0.0
booking_changes                    0.0
deposit_type                       0.0
agent                             13.7
company                           94.3
days_in_waiting_list               0.0
customer_type                      0.0
adr                                0.0
required_car_parking_spaces        0.0
total_of_special_requests          0.0
reservation_status                 0.0
reservation_status_date            0.0
dtype: float64

### Mengisi nilai hilang dengan suatu nilai

In [13]:
dataset["children"] = dataset["children"].fillna(dataset["children"].median())

In [14]:
dataset["children"].isna().sum()

np.int64(0)

### Mengubah tipe data kolom children

In [15]:
dataset["children"] = dataset["children"].astype("int")
dataset["children"].head()

0    0
1    0
2    0
3    0
4    0
Name: children, dtype: int64

### Mengecek dan membuang nilai duplikat

In [16]:
dataset.duplicated().sum()

np.int64(31994)

In [17]:
dataset1 = dataset.drop_duplicates()
dataset1.duplicated().sum()

np.int64(0)

## Transformasi Data

### Membuat Kolom Baru

In [18]:
dataset1["total_penghuni"] = dataset1["adults"] + dataset1["babies"] + dataset1["children"]

/tmp/ipython-input-18-1272015448.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1["total_penghuni"] = dataset1["adults"] + dataset1["babies"] + dataset1["children"]

In [19]:
dataset1["total_penghuni"]

0         2
1         2
2         1
3         1
4         2
         ..
119385    2
119386    3
119387    2
119388    2
119389    2
Name: total_penghuni, Length: 87396, dtype: int64

### Melakukan Encode

In [20]:
dataset1["is_resort"] = pd.get_dummies(dataset1["hotel"], drop_first = True)
dataset1["is_resort"].head()

/tmp/ipython-input-20-2405278624.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1["is_resort"] = pd.get_dummies(dataset1["hotel"], drop_first = True)

0    True
1    True
2    True
3    True
4    True
Name: is_resort, dtype: bool

### Membuat Kategori Baru (Diskretisasi)

In [21]:
def lead_time_category(x):

  if x <= 30:
    return "1mo"
  elif x <= 60:
    return "2mo"
  else:
    return ">3mo"

dataset1["lead_time_category"] = dataset1["lead_time"].apply(lead_time_category)
dataset1["lead_time_category"].head()

/tmp/ipython-input-21-3465192956.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1["lead_time_category"] = dataset1["lead_time"].apply(lead_time_category)

0    >3mo
1    >3mo
2     1mo
3     1mo
4     1mo
Name: lead_time_category, dtype: object

### Mengubah kategori

In [22]:
dataset1["co_status"] = dataset1["reservation_status"].map({"Check-Out" : "Success",
                                    "Canceled": "Not Success",
                                    "No-Show" : "Not Sucess"})
dataset1["co_status"].head()

/tmp/ipython-input-22-3393171246.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1["co_status"] = dataset1["reservation_status"].map({"Check-Out" : "Success",

0    Success
1    Success
2    Success
3    Success
4    Success
Name: co_status, dtype: object

### Pengubahan skala data

In [23]:
dataset1["adr_scaled"] = dataset1[["adr"]].apply(lambda x: (x - x.max())/ (x.max() - x.min()))

/tmp/ipython-input-23-3513975937.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1["adr_scaled"] = dataset1[["adr"]].apply(lambda x: (x - x.max())/ (x.max() - x.min()))

### Aggregasi Data

In [25]:
by_country = dataset1.groupby("country")[["lead_time", "total_penghuni", "adr"]].mean()
by_country.head()

          lead_time  total_penghuni         adr
country
ABW      126.000000        2.500000  128.340000
AGO       23.897661        1.836257  117.970029
AIA        0.000000        4.000000  265.000000
ALB       93.272727        1.909091   85.203636
AND       47.000000        2.714286  202.652857

### Pivot

In [26]:
pivot_lead_time = dataset1.pivot_table(index = "reservation_status",
                     columns = "hotel",
                     values = "lead_time",
                     aggfunc = "mean")
pivot_lead_time.head()

hotel               City Hotel  Resort Hotel
reservation_status
Canceled            104.133325    115.775616
Check-Out            67.387999     73.999115
No-Show              50.759358     60.011278

### Melt

In [27]:
pivot_lead_time.melt()

          hotel       value
0    City Hotel  104.133325
1    City Hotel   67.387999
2    City Hotel   50.759358
3  Resort Hotel  115.775616
4  Resort Hotel   73.999115
5  Resort Hotel   60.011278